### ISSUE TITLE
how i can make secrets.yml file ? 

### ISSUE THREAD

**Issue by Qasem-h** [blazeroot/videoshrimp#2]
plesae make a examlpe secrets.yml file
You will need to copy your keys to config/secrets.yml as pubnub_subscribe_key, pubnub_publish_key, pubnub_secret_key and you should create by yourself some unique pubnub_auth_key for s

**Comment by blazeroot** [comment]
Hi @Qasem-h,

I've added `secrets.yml.example`, you can find it [here](https://github.com/blazeroot/videoshrimp/blob/master/config/secrets.yml.example).

**Comment by Qasem-h** [comment]
thank you
